spring.application.name=grade_app1
spring.datasource.url=jdbc:sqlite:grades.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

server.port=8080